-- Problem 45: Triangular, pentagonal, and hexagonal
--
-- https://projecteuler.net/problem=45
-- 
-- Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
--
-- Triangle         Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
-- Pentagonal       Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
-- Hexagonal        Hn=n(2n−1)      1, 6, 15, 28, 45, ...
-- It can be verified that T285 = P165 = H143 = 40755.
--
-- Find the next triangle number that is also pentagonal and hexagonal.

import Data.List

triangle :: Integer -> Integer
triangle n = n * (n + 1) `div` 2

natural :: Double -> Bool
natural n = floor n == ceiling n

pentagonal :: Integer -> Bool
pentagonal n = natural $ (sqrt (24 * (fromIntegral n) + 1) + 1) / 6

hexagonal :: Integer -> Bool
hexagonal n = natural $ (sqrt (8 * (fromIntegral n) + 1) + 1) / 4

findNext n
    | (pentagonal $ triangle n) && hexagonal (triangle n) = triangle n
    | otherwise = findNext (n + 1) 

main = putStrLn $ show $ findNext 286
