-- Problem 44: Pentagon Numbers
--
-- https://projecteuler.net/problem=44
--
-- Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
--
-- 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
--
-- It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
--
-- Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; 
-- what is the value of D?

import Data.List

pentagon :: Integer -> Integer
pentagon n = n * (3 * n - 1) `div` 2

natural :: Double -> Bool
natural n = floor n == ceiling n

pentagonal :: Integer -> Bool
pentagonal n = natural $ (sqrt (24 * (fromIntegral n) + 1) + 1) / 6

minDiffs :: [Integer] -> [Integer]
minDiffs xs = sort [b - a | a <- xs, b <- xs, a < b, pentagonal (b + a), pentagonal (b - a)]

main = putStrLn $ show $ minDiffs [pentagon n | n <- [1..10000]]
